name: sociocredz
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get: ^3.26.0
  auto_size_text: ^2.1.0
  qr_flutter: ^3.2.0
  cached_network_image: ^2.5.1
  floating_bottom_navigation_bar: ^1.4.1
  flutter_svg: ^0.18.1
  expansion_card: ^0.1.0
  carousel_slider: ^3.0.0
  smooth_page_indicator: ^0.2.1
  google_sign_in: ^4.5.9
  firebase_auth: ^0.20.0+1 
  firebase_core: ^0.7.0
  get_storage: ^1.4.0
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
